tododo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/urls.py
from django.urls import path
from . import views


app_name = 'todolist'

urlpatterns = [
    path('', views.home, name='home'),
    path('login_view/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('register_completed/', views.register_completed, name='register_completed'),
    path('password_reset_email/', views.password_reset, name='password_reset_email' ),
    path('new_password_email/<str:uidb64>/<str:token>/', views.new_password_email, name='new_password_email'),
    path('new_password_invalid/', views.new_password_invalid, name='new_password_invalid'),
    path('password_reset_done/<str:uidb64>/', views.password_reset_done, name='password_reset_done'),
    path('invalid_email/', views.invalid_email, name='invalid_email'),
    path('password_reset_complete/', views.password_reset_complete, name='password_reset_complete'),
    path('required_active_user/', views.required_active_view, name='required_active_user'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<str:user_id>/', views.profile, name='profile'),
    path('money_view/<int:user_id>/', views.money_view, name='money_view'),
    path('money_view_add/<int:user_id>/', views.money_view_add, name='money_view_add'),
    path('todo_view/<int:user_id>/', views.todo_view, name='todo_view'),
    path('profile_settings/<int:user_id>/', views.profile_settings, name='profile_settings'),
    path('add_todo_title/<int:user_id>/', views.add_title_todo, name= 'add_title_todo'),
    path('add_todo_with_title/<int:user_id>', views.add_todo_with_title, name='add_todo_with_title'),
    path('delete_task/<int:user_id>/<int:todolist_id>/', views.delete_task, name='delete_task'),
    path('set_completed/<int:user_id>/<int:todolist_id>/', views.set_completed, name='set_completed'),
    path('edit_task/<int:user_id>/<int:todolist_id>', views.edit_task, name='edit_task'),
    path('edit_current_task/<int:user_id>/<int:title_id>/', views.edit_current_task, name='edit_current_task'),
    path('activate/<str:token>/', views.activation_user, name='activate'),
    path('dashboard/<int:user_id>/', views.dashboard, name='dashboard'),
]

templates/add_todo_title.html
<html data-bs-theme="light" lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Dashboard - Brand</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Akaya+Kanadaka&amp;display=swap">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static "css/untitled.css" %}">
</head>


<body class="bg-gradient-primary" style="background: rgb(46,45,136);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-flex">
                                <div class="flex-grow-1 bg-login-image" style="background: url(&quot;assets/img/dogs/449588878_1200076468099695_1720320468959886135_n.jpg&quot;) center / cover no-repeat;"></div>
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-4"></h4>
                                    </div>
                                    <form class="user" method='POST' action=''>
                                        {% csrf_token %}
                                        <div class="mb-3">{{form.as_p}}</div>
                                        
                                        <input type='submit' value='Update' class="btn btn-primary d-flex"/>
                                        </div>
                                        <hr>
                                    </form>
                                    <div class="text-center"><a class="small" href="{% url 'todolist:todo_view' user_id=user_id %}">Go back ...</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/bs-init.js"></script>
    <script src="assets/js/theme.js"></script>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">
{% load static %}
{% load widget_tweaks %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Dashboard - Brand</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Akaya+Kanadaka&amp;display=swap">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static "css/untitled.css" %}">
</head>

<body class="bg-gradient-primary" style="background: rgb(46,45,136);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-flex">
                                <div class="flex-grow-1 bg-login-image" style="background: url('{% static 'images/dogs/449588878_1200076468099695_1720320468959886135_n.jpg' %}') center / cover no-repeat;"></div>
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-4">Welcome Back!</h4>
                                        {% if messages %}
                                            <div class="alert alert-danger">
                                                {% for message in messages %}
                                                    {{ message }}
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                    </div>
                                    <form class="user" method= 'POST' action = ''>
                                        {% csrf_token %}
                                        <div class="col-sm-6">{% render_field user_form.email placeholder="email"  autocomplete='email' class+="form-control form-control-user" %}</div>
                                        <div class="col-sm-6">{% render_field user_form.password placeholder="password" class+="form-control form-control-user" %}</div>
                                        <div class="mb-3">
                                            <div class="custom-checkbox small">
                                                <div class="form-check"><input class="form-check-input" type="checkbox" id="formCheck-1"><label class="form-check-label" for="formCheck-1">Remember Me</label></div>
                                            </div>
                                        </div><button class="btn btn-primary d-block btn-user w-100" type="submit">Login</button>
                                        {% load socialaccount %}
                                        <hr><a class="btn btn-primary d-block btn-google btn-user w-100 mb-2" href="{% provider_login_url 'google' %}"><i class="fab fa-google"></i>&nbsp; Login with Google</a><a class="btn btn-primary d-block btn-facebook btn-user w-100" href="{% provider_login_url 'facebook' %}"><i class="fab fa-facebook-f"></i>&nbsp; Login with Facebook</a>
                                        <hr>
                                    </form>
                                    <div class="text-center"><a class="small" href="{% url 'todolist:password_reset_email' %}">Forgot Password?</a></div>
                                    <div class="text-center"><a class="small" href="{% url 'todolist:register' %}">Create an Account!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
</body>

</html>

templates/money_view_add.html
{% extends "main.html" %}

{% block content %}

<form method= 'POST' action = ''>
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-primary btn-sm d-none d-sm-inline-block" type="submit" value='Add' style="background: rgb(46,45,136);"><i class="fas fa-download fa-sm text-white-50">

    </form>


{% endblock content %}

templates/navbar.html
{% load static %}
{% load tz %}
<body id="page-top">
    <div id="wrapper">
        <nav class="navbar align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0 navbar-dark" style="background: rgb(46,45,136);">
            <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{% url 'todolist:home' %}">
                    <div class="sidebar-brand-icon rotate-n-15"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="1em" height="1em" fill="currentColor" style="font-size: 35px;">
                            <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. -->
                            <path d="M152.1 38.2c9.9 8.9 10.7 24 1.8 33.9l-72 80c-4.4 4.9-10.6 7.8-17.2 7.9s-12.9-2.4-17.6-7L7 113C-2.3 103.6-2.3 88.4 7 79s24.6-9.4 33.9 0l22.1 22.1 55.1-61.2c8.9-9.9 24-10.7 33.9-1.8zm0 160c9.9 8.9 10.7 24 1.8 33.9l-72 80c-4.4 4.9-10.6 7.8-17.2 7.9s-12.9-2.4-17.6-7L7 273c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l22.1 22.1 55.1-61.2c8.9-9.9 24-10.7 33.9-1.8zM224 96c0-17.7 14.3-32 32-32H480c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-17.7 0-32-14.3-32-32zm0 160c0-17.7 14.3-32 32-32H480c17.7 0 32 14.3 32 32s-14.3 32-32 32H256c-17.7 0-32-14.3-32-32zM160 416c0-17.7 14.3-32 32-32H480c17.7 0 32 14.3 32 32s-14.3 32-32 32H192c-17.7 0-32-14.3-32-32zM48 368a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"></path>
                        </svg></div>
                    <div class="sidebar-brand-text mx-3"><span style="font-family: 'Akaya Kanadaka', serif;font-size: 20px;">TODODO</span></div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <li class="nav-item"><a class="nav-link active" href={% url 'todolist:dashboard' user_id=user_id %}><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a></li>
                    <li class="nav-item"><a class="nav-link" href={% url 'todolist:profile' user_id=user_id %}><i class="fas fa-user"></i><span>Profile</span></a></li>
                    <li class="nav-item"><a class="nav-link" href={% url 'todolist:money_view' user_id=user_id %}><i class="fas fa-table"></i><span>Money</span></a></li>
                    <li class="nav-item"><a class="nav-link" href={% url 'todolist:todo_view' user_id=user_id %}><i class="fas fa-list-ul"></i><span>Todo List</span></a></li>
                    <li class="nav-item"><a class="nav-link" href={% url 'todolist:profile_settings' user_id=user_id %}><i class="fas fa-check"></i><span>Settings</span></a></li>
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-expand bg-white shadow mb-4 topbar">
                    <div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle me-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                        
                        <ul class="navbar-nav flex-nowrap ms-auto">
                            
                            <li class="nav-item dropdown no-arrow mx-1">
                                <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#"><span class="badge bg-danger badge-counter"></span><i class="fas fa-bell fa-fw"></i></a>
                                    <div class="dropdown-menu dropdown-menu-end dropdown-list animated--grow-in">
                                        <h6 class="dropdown-header">alerts center</h6><a class="dropdown-item d-flex align-items-center" href="{% url 'todolist:todo_view' user_id=user_id %}">
                                            <div class="me-3">
                                                <div class="bg-primary icon-circle"><i class="fas fa-file-alt text-white"></i></div>
                                            </div>
                                            <div><span class="small text-gray-500">{% now "DATE_FORMAT" %}</span>
                                                <p>You have {{ task_count }} tasks.</p>
                                            </div>
                                        
                                            
                                        </a><a class="dropdown-item d-flex align-items-center" href="{% url 'todolist:todo_view' user_id=user_id %}">
                                            <div class="me-3">
                                                <div class="bg-warning icon-circle"><i class="fas fa-exclamation-triangle text-white"></i></div>
                                            </div>
                                            <div><span class="small text-gray-500">{% now "DATE_FORMAT" %}</span>
                                                <p>You have {{ task_important_count }} Important task</p>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item dropdown no-arrow mx-1">
                                <div class="shadow dropdown-list dropdown-menu dropdown-menu-end" aria-labelledby="alertsDropdown"></div>
                            </li>
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow"><a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#"><span class="d-none d-lg-inline me-2 text-gray-600 small">Wander Szybki Pies</span><img class="border rounded-circle img-profile" src="{{ user.avatar.url }}"></a>
                                    <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in"><a class="dropdown-item" href="{% url 'todolist:profile' user_id=user_id %}"><i class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Profile</a><a class="dropdown-item" href="{% url 'todolist:profile_settings' user_id=user_id %}"><i class="fas fa-cogs fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Settings</a><a class="dropdown-item" href="{% url 'todolist:home' %}"><i class="fas fa-list fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Activity log</a>
                                        <div class="dropdown-divider"></div>
                                            <a href="#" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                                <i class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Logout
                                            </a>
                                            <form id="logout-form" method="post" action="{% url 'todolist:logout' %}" style="display: none;">
                                                {% csrf_token %}
                                            </form>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>

templates/send_email.html
<!-- templates/send_email.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Send Email</title>
</head>
<body>
    <h1>Send Test Email</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Send Email</button>
    </form>
</body>
</html>

templates/todo_view.html
{% extends "main.html" %}
{% load static %}
{% block content %}

                <div class="container-fluid">
                    <h3 class="text-primary mb-4" style="text-align: center;box-shadow: 1px 1px 9px;border-radius: 18px;">Todo List</h3>
                    <div class="row mb-3">
                        <div class="col-lg-4">
                            <div class="card mb-3"></div>
                            <div class="card shadow mb-4">
                                <div class="card shadow mb-4">
                                    <div class="card-body d-flex justify-content-center"><a href="{% url 'todolist:add_todo_with_title' user_id=user_id %}" class="btn btn-primary pulse animated" type="button" style="text-align: left;box-shadow: 1px 1px 16px var(--bs-btn-border-color);">Add Todo</a></div>
                                    <div class="card-body d-flex justify-content-center"><a href="{% url 'todolist:add_title_todo' user_id=user_id %}" class="btn btn-primary pulse animated" type="button" style="text-align: left;box-shadow: 1px 1px 16px var(--bs-btn-border-color);">Add Title</a></div>
                                    <div style="padding: 5px;margin: 5px;background: rgba(133,135,150,0);border: 1px solid rgba(133,135,150,0);border-radius: 15px;box-shadow: 1px 1px 6px rgb(0,30,255);">
                                        <p class="align-items-center align-content-center" style="color: var(--bs-emphasis-color);font-weight: bold;font-size: 16px;margin-bottom: -3px;text-align: center;">This Month: {{ tasks_this_month_count }}<a class="float-end" href="#" style="text-decoration: none;"></a><a href="#" style="text-decoration: none;"></a></p>
                                        <p class="align-items-center align-content-center" style="color: var(--bs-light-text-emphasis);font-weight: bold;font-size: 12px;text-align: center;margin-bottom: -1px;">Completed: {{ tasks_completed_this_month_count }}<a class="float-end" href="#" style="text-decoration: none;"></a><a href="#" style="text-decoration: none;"></a></p>
                                        <p class="align-items-center align-content-center" style="color: var(--bs-emphasis-color);font-weight: bold;font-size: 18px;text-align: center;margin-bottom: -1px;">Overall: {{ overall_tasks }}<a class="float-end" href="#" style="text-decoration: none;"></a><a href="#" style="text-decoration: none;"></a></p>
                                        <p class="align-items-center align-content-center" style="color: var(--bs-light-text-emphasis);font-weight: bold;font-size: 12px;text-align: center;margin-bottom: -1px;">Completed: {{ overall_tasks_completed }}<br><a href="#" style="text-decoration: none;"></a></p>
                                    </div>
                                </div>
                            </div>
                            <div class="card shadow mb-4">
                                <div class="card-body">
                                    <div class="text-primary" style="background: var(--bs-body-bg);border-radius: 14px;box-shadow: 1px 1px 7px var(--bs-link-color);">
                                        <h4 class="fw-bold text-primary" data-aos="zoom-in-left" data-aos-duration="300" data-aos-delay="250" style="color: rgb(133,135,150);border-radius: 14px;margin: 10px;text-align: center;font-family: Nunito, sans-serif;">Important</h4>
                                    </div>
                                </div>
                                {% for important_task in important_tasks|dictsortreversed:"active" %}
                                {% if not important_task.active %}
                                <div data-aos="zoom-in-left" data-aos-duration="350" data-aos-delay="550" style="padding: 5px;margin: 5px;background: rgba(133,135,150,0);border: 1px solid rgba(133,135,150,0);border-radius: 15px;box-shadow: 1px 1px 5px;">           
                                    <p class="align-items-center align-content-center" style="color: #22c232;font-weight: bold;font-size: 16px;margin-bottom: 0px;margin-top: 2px;padding: 5px;">{{ important_task.task }} (completed)<a href="{% url 'todolist:delete_task' user_id=user_id todolist_id=important_task.id %}" style="text-decoration: none;"></a><a href={% url 'todolist:delete_task' user_id=user_id todolist_id=important_task.id %} style="text-decoration: none;"><i class="fas fa-times float-end" style="font-size: 20px;"></i></a><a href={% url 'todolist:edit_task' user_id=user_id todolist_id=important_task.id %}><i class="far fa-edit" style="margin-left: 8px;color: rgb(0,65,255);"></i></a></p></p>
                                </div>
                                {% else %}
                                <div data-aos="zoom-in-left" data-aos-duration="350" data-aos-delay="550" style="padding: 5px;margin: 5px;background: rgba(133,135,150,0);border: 1px solid rgba(133,135,150,0);border-radius: 15px;box-shadow: 1px 1px 5px;">
                                    <p class="align-items-center align-content-center" style="color: #ff0000;font-weight: bold;font-size: 16px;">{{important_task.task}}<a class="float-end" href="{% url 'todolist:set_completed' user_id=user_id todolist_id=important_task.id %}" style="text-decoration: none;"><i class="fas fa-check" style="font-size: 17px;margin-left: 13px;"></i></a><a href={% url 'todolist:delete_task' user_id=user_id todolist_id=important_task.id %} style="text-decoration: none;"><i class="fas fa-times float-end" style="font-size: 20px;"></i></a><a href={% url 'todolist:edit_task' user_id=user_id todolist_id=important_task.id %}><i class="far fa-edit" style="margin-left: 8px;color: rgb(0,65,255);"></i></a></p>
                                </div> 
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="col-lg-8 col-xl-4 col-xxl-4">
                            <div class="card mb-3"></div>
                            <h3 class="text-primary mb-4" style="text-align: center;box-shadow: 1px 1px 9px;border-radius: 18px;">{{month}}</h3>
                            <div class="card shadow mb-4">
                                {% for title, tasks in title_task_map.items %}
                                
                                <div style="padding: 5px;margin: 5px;background: rgba(133,135,150,0);border: 1px solid rgba(133,135,150,0);border-radius: 15px;box-shadow: 1px 1px 5px;">
                                    
                                    <p class="text-primary align-items-center align-content-center" style="color: var(--bs-secondary-text-emphasis);font-weight: bold;font-size: 30px;margin-bottom: -3px;text-align: center;">{{ title.title }}<a class="float-end" href="{% url 'todolist:edit_current_task' user_id=user_id title_id=title.id%}"><i class="fas fa-plus text-primary-emphasis" data-aos="fade-down" data-aos-duration="200" data-aos-delay="200" style="color: #000000;"></i></a></p>
                                    {% for task in tasks %}
                                    
                                {% if not task.active %}
                
                                    <p class="align-items-center align-content-center" style="color: #22c232;font-weight: bold;font-size: 16px;margin-bottom: 0px;margin-top: 2px;padding: 5px;"><a href="{% url 'todolist:edit_task' user_id=user_id todolist_id=task.id%}"><i class="far fa-edit" style="margin-left: 8px;color: rgb(0,65,255);"></a></i>{{task.task}} (completed)<a href="{% url 'todolist:delete_task' user_id=user_id todolist_id=task.id %}" style="text-decoration: none;"><i class="fas fa-times float-end" style="font-size: 20px;"></i></a></p>
                                    <hr style="margin-top: -1px;margin-bottom: -4px;">

                                {% elif not task.important %}
                                    
                                    <p class="align-items-center align-content-center" data-aos="fade" data-aos-duration="100" data-aos-delay="100" style="color: var(--bs-dark-text-emphasis);font-weight: bold;font-size: 16px;margin-bottom: 0px;padding: 5px;"><a href="{% url 'todolist:edit_task' user_id=user_id todolist_id=task.id%}"><i class="far fa-edit" style="margin-left: 8px;color: rgb(0,65,255);"></a></i>{{ task.task }}<a class="float-end" href="{% url 'todolist:set_completed' user_id=user_id todolist_id=task.id %}" style="text-decoration: none;"><i class="fas fa-check" style="font-size: 17px;margin-left: 13px;"></i></a><a href="{% url 'todolist:delete_task' user_id=user_id todolist_id=task.id %}" style="text-decoration: none;"><i class="fas fa-times float-end" style="font-size: 20px;"></i></a></p>
                                    <hr style="margin-top: -1px;margin-bottom: -4px;">
                                    
                                {% else %}
                                    
                                    <p class="align-items-center align-content-center" data-aos="fade" data-aos-duration="100" data-aos-delay="100" style="color: #ff0000;font-weight: bold;font-size: 16px;margin-bottom: 0px;padding: 5px;"><a href=""><i class="far fa-edit" style="margin-left: 8px;color: rgb(0,65,255);"></a></i>{{task.task}}<a class="float-end" href="{% url 'todolist:set_completed' user_id=user_id todolist_id=task.id %}" style="text-decoration: none;"><i class="fas fa-check" style="font-size: 17px;margin-left: 13px;"></i></a><a href="{% url 'todolist:delete_task' user_id=user_id todolist_id=task.id %}" style="text-decoration: none;"><i class="fas fa-times float-end" style="font-size: 20px;"></i></a></p>
                                    <hr style="margin-top: -1px;margin-bottom: -4px;">

                                {% endif %}
                                    
                                {% endfor %}

                                </div>
                                {% endfor %}
                                
                            </div>
                            
                            
                        </div>
                        <div class="col-lg-8 col-xl-4 col-xxl-4">
                            <div class="card mb-3"></div>
                            <h3 class="text-primary mb-4" style="text-align: center;box-shadow: 1px 1px 9px;border-radius: 18px;">Overview</h3>
                            <div class="card shadow mb-4">
                                <div class="card-header d-flex">
                                        <h6 class="text-primary fw-bold m-0">Task Completed This month</h6>
                                    <div class="dropdown no-arrow">
                                        
                                    </div>
                                </div>
                                {% if plot_path is not None %}
                                <div class="card-body">
                                    <img src="data:image/png;base64,{{ plot_path }}" alt="Wykres" style="max-width: 100%; height: auto;"> </img>
                                </div>
                                {% else %}
                                <p> No data to display </p>
                                {% endif %}
                            </div>
                            <div class="card mb-3"></div>
                            <div class="card shadow mb-4">
                                <div class="card-header d-flex">
                                        <h6 class="text-primary fw-bold m-0">Completed/Active</h6>
                                    <div class="dropdown no-arrow">
                                        
                                    </div>
                                </div>
                                {% if plot_path_pie is not None %}
                                <div class="card-body">
                                    <img src="data:image/png;base64,{{ plot_path_pie }}" style="max-width: 100%; height: auto;"> </img>
                                </div>
                                {% else %}
                                <p> No data to display </p>
                                {% endif %}
                            </div>
                            <div class="card mb-3"></div>
                            <div class="card shadow mb-4">
                                <div class="card-header d-flex">
                                        <h6 class="text-primary fw-bold m-0">Overall Tasks grouped</h6>
                                    <div class="dropdown no-arrow">
                                        
                                    </div>
                                </div>
                                {% if plot_path_pie_task is not None %}
                                <div class="card-body">
                                    <img src="data:image/png;base64,{{ plot_path_pie_task }}" alt="Wykres" style="max-width: 100%; height: auto;"> </img>
                                </div>
                                {% else %}
                                <p> No data to display </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Copyright © no-ppp 2024</span></div>
                </div>
            </footer>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
</body>
{% endblock %}